sonar.projectKey=prem2230_microservices
sonar.organization=prem2230
sonar.projectName=food-delivery-app

sonar.sources=microservices,client,server
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**

sonar.qualitygate.wait=true
