sonar.projectKey=prem2230_microservices
sonar.organization=prem2230
sonar.projectName=microservices

sonar.sources=user-service,food-service,order-service,restaurant-service,api-gateway
sonar.exclusions=**/node_modules/**,**/.next/**,**/coverage/**

sonar.qualitygate.wait=true
